name: Docker Image CI

on:
  push:
    branches-ignore: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      max-parallel: 2
      fail-fast: true
      matrix:
        include:
          - centos_version: "7"
            python_version: "3.6.15"
            experimental: true
          - centos_version: "7"
            python_version: "3.7.17"
            experimental: true
          - centos_version: "7"
            python_version: "3.10.12"
            experimental: true
          - centos_version: "7"
            python_version: "3.11.5"
            experimental: true
          - centos_version: "7"
            python_version: "3.12.0rc2"
            experimental: true

    env:
      QUICK_BUILD: false
      CENTOS_VERSION: ${{ matrix.centos_version }}
      PYTHON_VERSION: ${{ matrix.python_version }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: bash src/build_image.sh
      - name: Test the image
        run: bash src/test_image.sh
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the Image
        run: |
          docker tag ${DOCKERHUB_USERNAME}/centos-${CENTOS_VERSION}-python:${PYTHON_VERSION} ${DOCKERHUB_USERNAME}/centos-${CENTOS_VERSION}-python:${PYTHON_VERSION}-temporary
          docker push ${DOCKERHUB_USERNAME}/centos-${CENTOS_VERSION}-python:${PYTHON_VERSION}-temporary
