name: Docker Image CI

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

env:
  QUICK_BUILD: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        centos_version: ["7", "8"]
        python_version: ["3.10.12", "3.11.5", "3.12.0b4"]
    env:
      CENTOS_VERSION: ${{ matrix.centos_version }}
      PYTHON_VERSION: ${{ matrix.python_version }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: bash src/build_image.sh
      - name: Test the image
        run: bash src/test_image.sh
